//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebShipping.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ForwarderDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ForwarderDBEntities object using the connection string found in the 'ForwarderDBEntities' section of the application configuration file.
        /// </summary>
        public ForwarderDBEntities() : base("name=ForwarderDBEntities", "ForwarderDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ForwarderDBEntities object.
        /// </summary>
        public ForwarderDBEntities(string connectionString) : base(connectionString, "ForwarderDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ForwarderDBEntities object.
        /// </summary>
        public ForwarderDBEntities(EntityConnection connection) : base(connection, "ForwarderDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<contact> contacts
        {
            get
            {
                if ((_contacts == null))
                {
                    _contacts = base.CreateObjectSet<contact>("contacts");
                }
                return _contacts;
            }
        }
        private ObjectSet<contact> _contacts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the contacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontacts(contact contact)
        {
            base.AddObject("contacts", contact);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Models", Name="contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new contact object.
        /// </summary>
        /// <param name="contact_id">Initial value of the contact_id property.</param>
        /// <param name="contact_name">Initial value of the contact_name property.</param>
        public static contact Createcontact(global::System.Int32 contact_id, global::System.String contact_name)
        {
            contact contact = new contact();
            contact.contact_id = contact_id;
            contact.contact_name = contact_name;
            return contact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 contact_id
        {
            get
            {
                return _contact_id;
            }
            set
            {
                if (_contact_id != value)
                {
                    Oncontact_idChanging(value);
                    ReportPropertyChanging("contact_id");
                    _contact_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("contact_id");
                    Oncontact_idChanged();
                }
            }
        }
        private global::System.Int32 _contact_id;
        partial void Oncontact_idChanging(global::System.Int32 value);
        partial void Oncontact_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contact_name
        {
            get
            {
                return _contact_name;
            }
            set
            {
                Oncontact_nameChanging(value);
                ReportPropertyChanging("contact_name");
                _contact_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contact_name");
                Oncontact_nameChanged();
            }
        }
        private global::System.String _contact_name;
        partial void Oncontact_nameChanging(global::System.String value);
        partial void Oncontact_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accounting_id1
        {
            get
            {
                return _accounting_id1;
            }
            set
            {
                Onaccounting_id1Changing(value);
                ReportPropertyChanging("accounting_id1");
                _accounting_id1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accounting_id1");
                Onaccounting_id1Changed();
            }
        }
        private global::System.String _accounting_id1;
        partial void Onaccounting_id1Changing(global::System.String value);
        partial void Onaccounting_id1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accounting_id2
        {
            get
            {
                return _accounting_id2;
            }
            set
            {
                Onaccounting_id2Changing(value);
                ReportPropertyChanging("accounting_id2");
                _accounting_id2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accounting_id2");
                Onaccounting_id2Changed();
            }
        }
        private global::System.String _accounting_id2;
        partial void Onaccounting_id2Changing(global::System.String value);
        partial void Onaccounting_id2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vat
        {
            get
            {
                return _vat;
            }
            set
            {
                OnvatChanging(value);
                ReportPropertyChanging("vat");
                _vat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vat");
                OnvatChanged();
            }
        }
        private global::System.String _vat;
        partial void OnvatChanging(global::System.String value);
        partial void OnvatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sales_id
        {
            get
            {
                return _sales_id;
            }
            set
            {
                Onsales_idChanging(value);
                ReportPropertyChanging("sales_id");
                _sales_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sales_id");
                Onsales_idChanged();
            }
        }
        private Nullable<global::System.Int32> _sales_id;
        partial void Onsales_idChanging(Nullable<global::System.Int32> value);
        partial void Onsales_idChanged();

        #endregion

    
    }

    #endregion

    
}
